# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"addition": "00_arithmetic.ipynb",
         "subtraction": "00_arithmetic.ipynb",
         "multiplication": "00_arithmetic.ipynb",
         "division": "00_arithmetic.ipynb"}

modules = ["arithmetic.py"]

doc_url = "https://alonsosilvaallende.github.io/odsc_demo/"

git_url = "https://github.com/alonsosilvaallende/odsc_demo/tree/main/"

def custom_doc_links(name): return None
